### ISSUE TITLE
Document filter usage

### ISSUE THREAD

**Issue by ptere** [thingsapi/things-cli#12]
**Goal**
- As a user of things-cli
- I want to export content from some projects but not others
- so that I can manage that content elsewhere

**Suggested approach**
In order to achieve this goal I suggest to add examples to the Readme showing usage of the project, area, and tag filters.

**Additional context**
The CLI offers these arguments:

```
  -p FILTER_PROJECT, --filter-project FILTER_PROJECT
                        filter by project
  -a FILTER_AREA, --filter-area FILTER_AREA
                        filter by area
  -t FILTER_TAG, --filtertag FILTER_TAG
                        filter by tag
```

however I haven't been able to get any data out when using the `-p` or `-a` filters. I'm not clear if they require a name or a [UUID](https://github.com/thingsapi/things.py/blob/f31316597748a75e1b13c22760f620e5be329e19/things/api.py#L61), but I've tried both and always get empty results.

**Comment by jbilligmeier** [comment]
@ptere I had the same question, and I figured out from the api that it expects the UUID of the area. If you "share" an area, the long random looking string is what you can use with -a to filter

**Comment by ptere** [comment]
Thanks! I thought I had tried that and wasn't having luck, but I tried again on the latest version and it's working fine. Appreciate it.
