### ISSUE TITLE
Will no longer install with Python 3.12

### ISSUE THREAD

**Issue by chadleap** [thingsapi/things-cli#18]
This package will no longer install due to the [imp module being deprecated from Python 3.12](https://docs.python.org/3.11/library/imp.html)

`ModuleNotFoundError: No module named 'imp'`

**Comment by AlexanderWillner** [comment]
Thanks, indeed: https://github.com/ronaldoussoren/py2app/issues/496

**Comment by AlexanderWillner** [comment]
fyi: I manually removed the deprecated dependency locally (waiting for an upstream fix though) and it seems the installations works fine and the library seems to work with Python 3.12 (based on the unit tests).

**Comment by mbhutton** [comment]
The current version of things-cli (0.2.1) is now working fine with current version of Python (3.13.0). (Not retested with Python 3.12).

Seems to have been resolved upstream in py2app, where the release notes mention now supporting Python 3.13: https://github.com/ronaldoussoren/py2app/releases/tag/v0.28.8

Based on that, I'd suggest closing this issue.
