### ISSUE TITLE
logbook shows ALL completed tasks

### ISSUE THREAD

**Issue by dominik42** [thingsapi/things-cli#3]
**To Reproduce**
1. things-cli logbook
=> all completed tasks are shown

**Expected behavior**
As `things-cli --help` mentioned, only tasks completed today should be shown!

**Additional context**
things-cli @ MacOS 10.15.7 (Catalina) installed by `pip3 install things-cli` 
Python 2.7.16

things.sh did it right: only tasks completed today are shown.

**Comment by AlexanderWillner** [comment]
Indeed. What about having a command like `logtoday` that replicates the `things.sh` behaviour?

**Comment by AlexanderWillner** [comment]
Fixed, just added the new command.

**Comment by AlexanderWillner** [comment]
Didn't push the code, just the new version if the cli. Here we are: https://github.com/thingsapi/things-cli/commit/392f83f890f463942be5bc0c41f7571160172eb4

**Comment by dominik42** [comment]
BTW, seems that we share the same book shelf 😀

✅    Being more efficient: David Allen “Getting Things Done“
✅    Being more effective: Stephen R. Covey “The 7 Habits of Highly Effective People“
    Being more focused: Cal Newport “Deep Work” and Gary Keller “The One Thing“
    Being more energized: Jake Knapp, John Zeratsky “Make Time“
    Being more performing: Fredmund Malik “Managing Performing Living“
✅    Being more Zen: Leo Babauta „Essential Zen Habits: Mastering the Art of Change, Briefly“
✅    Being a better coder: Robert C. Martin “Clean Code“
    Being a better presenter
✅        Nancy Duarte “Slide:ology“
✅        Garr Reynolds “Presentation Zen” and “Presentation Zen Design“

**Comment by AlexanderWillner** [comment]
> Finished processing dependencies for things-cli==0.1.1

As your log says it the CLI depends on `things.py 0.0.12` I assume you're to run `git pull` first. The current version depends on `0.0.13`: https://github.com/thingsapi/things-cli/blob/master/requirements.txt#L2. I assume at the deployed version via `pip3 install things-cli` should also work.

> BTW, seems that we share the same book shelf 😀

Cool! However, maybe you're just read way more books than me ;)

**Comment by dominik42** [comment]
ok, will try this today ...
Another issue: if the things-cli runs from a MacOS cronjon (created via `crontab -e`) it seems, that the script doesn't allow to access the ThingsDB files.... It returns 0 for every command. Any suggestions ?

**Comment by dominik42** [comment]
Now it works but I have to manually uninstall things.py and things-cli via pip3 completely.
After `pip3 install things-cli` it comes with the proper versions and the new command `logtoday`.
I solved the issues regarding my cron job by using absolut path to the things-cli script.

THANKS !

**Comment by dominik42** [comment]
Just wanted to try the new `--gant` feature mentioned in the README.md ... but error    
`error: unrecognized arguments: --gantt` ... do we need a new issue ?

**Comment by AlexanderWillner** [comment]
just pushed version 0.1.2

**Comment by dominik42** [comment]
Cool ... works ... and now I know mermaid-js 😄 
`Commit 04:14` ....  "der frühe Vogel" ?  😜 
Greetings from Saxony
