### ISSUE TITLE
command for tasks created today

### ISSUE THREAD

**Issue by dominik42** [thingsapi/things-cli#5]
**Goal**
- As a user
- I want to know how many task I've created today
- for statistically reasons

**Suggested approach**
In order to achieve this goal I suggest to implement a command `createdtoday`similar to `logtoday`

**Additional context**
Should be extracted by something like
`select * from TMTask where date(creationDate,'unixepoch') = '2021-11-30';`

**Comment by AlexanderWillner** [comment]
released. thanks.
